### PR TITLE
Unit tests revision

### PR DESCRIPTION
**Pull request by nigrosimone**
- Enable redis.so by adding redis.so into php.ini
- Enable memcached.so by adding memcached.so into php.ini
- Enable Apc(u) cli because test run under cli env

### CODE REVIEW

**Comment by szepeviktor** [comment]
OK.

~~No need to hack with files: https://docs.travis-ci.com/user/languages/php/#Enabling-preinstalled-PHP-extensions~~

Should we also enable those PHP confs?

**Comment by nigrosimone** [comment]
no problem, it's the same...

**Comment by nigrosimone** [comment]
> Should we also enable those PHP confs?

memcache and redis require only the `*.so` inclusion into php.ini. Apc(u) seem need `apc.enable_cli = 1` into php.ini because tests run under cli.

**Comment by nigrosimone** [comment]
all seem ok... the skipped tests are APC when the php version is 5.5,5.6,7.* and APCu when php is 5.3,5.4.

**Comment by szepeviktor** [comment]
Please squeeze your commits and provide a small description. 

Thanks. 

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
Could we make WP use mysqli?
There are errors in the test.
https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/239288596

Or enable the mysqli extension?

**Comment by nigrosimone** [comment]
>  There are errors in the test.

it's just a deprecation warning..

**Comment by szepeviktor** [comment]
How about this one? `sh: 1: -t: not found`
and
https://github.com/WordPress/WordPress/blob/4cf5550d8d7f227d760f779f250a8fb2cfa2c8c9/wp-includes/wp-db.php#L632-L646
but
https://github.com/szepeviktor/w3-total-cache-fixed/pull/497/files

**Pull request merged**
