### PR TITLE
add w3tc_pgcache_lifetime filter

### PR DESCRIPTION
**Pull request by todiadiyatmo**
Adding `w3tc_pgcache_lifetime`

example usage : 

```
add_filter('w3tc_pgcache_lifetime', function($time) {
    // you can add conditional pgcache.lifetime
    // for example homepage can be lower lifetime while single page can be set forever

    return $time;
});
```

### CODE REVIEW

**Comment by cesco69** [comment]
I propose to pass two parameter, $time and $request_uri
```php
add_filter('w3tc_pgcache_lifetime', function($request_uri, $time) {
    // you can add conditional pgcache.lifetime
    if( $request_uri == '/my-spacial-page' ){
        $time = $time + 60;
    }
    return $time;
});
```

**Comment by todiadiyatmo** [comment]
@cesco69 seems good, but it seems not working with page enhanced mode... is there any guide to do unit test with this plugin ?

**Comment by todiadiyatmo** [comment]
@cesco69 added request URI

Upadate :  
- code tested in 4.6.1 and worked
- It was previously broken in 4.5* (not remeber exactly)

**Comment by amiga-500** [comment]
This is a nice, quick, and cute little gift for non-disk page cache users.  

In the future i could write a simple UI (and placed on the page cache area) so users can give the request uris (regex style) and times there instead of having to code it in.  And from there it will then hook into this new filter to process them.

**Comment by charlesLF** [comment]
Nice addition. Very useful. :+1:

**Comment by todiadiyatmo** [comment]
@amiga-500 IMHO the person do stuff like this is very tech savvy person, so better document this into a proper wiki and let them have fun :)

**Comment by todiadiyatmo** [comment]
Btw the file generic also have an "expiration" params, is this  working ? 

```
  case 'file_generic':
                    if (w3_get_blog_id() == 0)
                        $flush_dir = W3TC_CACHE_PAGE_ENHANCED_DIR;
                    else
                        $flush_dir = W3TC_CACHE_PAGE_ENHANCED_DIR . '/' . w3_get_domain(w3_get_host());

                    $engineConfig = array(
                        'exclude' => array(
                            '.htaccess'
                        ),
                        'expire' => $this->_lifetime,
                        'cache_dir' => W3TC_CACHE_PAGE_ENHANCED_DIR,
                        'locking' => $this->_config->get_boolean('pgcache.file.locking'),
                        'flush_timelimit' => $this->_config->get_integer('timelimit.cache_flush'),
                        'flush_dir' => $flush_dir,
                    );
                    break;
```

**Comment by charlesLF** [comment]
I think the order of the arguments passed to apply_filters should be reversed.
i.e.: `this->_request_uri` should be the 2nd parameter passed, not the first.

Check my comment here: https://github.com/todiadiyatmo/fix-w3tc/pull/1#commitcomment-19024192

**Comment by amiga-500** [comment]
> Btw the file generic also have an "expiration" params, is this working ? 
Yup.  you are correct.  I forgot about that.  It's specifically for the non-enhanced "Disk" mode (aka `file_generic`).  So technically you can also [update this area](https://github.com/szepeviktor/fix-w3tc/blob/master/lib/W3/PgCache.php#L142-L143) to reflect the same feature so that people who used any cache mode (except "Disk Enhanced" would have access to modifying a page's lifespan.

**Comment by amiga-500** [comment]
> Btw the file generic also have an "expiration" params, is this working ? 

@todiadiyatmo , yup.  For `file_generic` (aka the non-enhanced disk mode) it has that ability for pages.  I forgot about that.  If i recall it stores that information inside the page when written to disk and when a request is made it reads that entire cached page into buffer, strips out this meta info, compares times (if old it generates a new page), and then sends back the page buffer to the user.  So your ability to customize page-level lifespans would work for all cache modes except `Disk Enhanced`.  Awesome!

And although it's subjective on the ordering of the parameters i can see the logic of having $request_uri as the 2nd parameter, not the first.  I could then create a filter that preferred to only want the time so i could then use Wordpress functions to better identify the page being requested instead of using $request_uri, since the $request_uri can potentially include query details (e.g. "?foo=bar"), and if one doesn't do a compare correctly may miss setting the time for a given page.  Obviously, one can just ignore using the $request_uri parameter (if it remained as the 1st) but it would just be cleaner to have it as the 2nd parameter so coders can decide if they want a function declaration that only uses 1 (the required: $time) or the 2nd (optional: $request_uri) parameter.  For example:

```php
add_filter('w3tc_pgcache_lifetime', "my_handler"); // callback fn uses only 1 (the one required) of the 2 available parameters

function my_handler($time)
{
     $post = get_post();
     switch ($post->ID)
     {
          case 2:
               $time = 60;
               break;
          case 301:
               $ time = 1800;
               break;
          default:
               $time = 3600;
     }

    return $time;
}
```

**Comment by todiadiyatmo** [comment]
@amiga-500 
Already update with time as first params,
Thanks for the clear explanation, really appreciate it !

Regards,
Todi

**Comment by charlesLF** [comment]
@amiga-500, it's more than just semantics.
When you write:
```php
$this->_lifetime = apply_filters('w3tc_pgcache_lifetime', $this->_request_uri, $this->_lifetime);
```
And if you don't have any function that is actually returning something on the filter (aka what most w3tc users will have by default, then this would effectively translate to
`$this->_lifetime = $this->_request_uri` ... which is not good.

**Comment by amiga-500** [comment]
Ahhh thanks @charlesLF ... learned something new!

**Comment by dmarkowicz** [comment]
There is a problem with this PR
```
( ! ) Fatal error: Uncaught Error: Call to undefined function apply_filters() in C:\myproject\wp-content\plugins\w3-total-cache\lib\W3\PgCache.php on line 152
( ! ) Error: Call to undefined function apply_filters() in C:\myproject\wp-content\plugins\w3-total-cache\lib\W3\PgCache.php on line 152
Call Stack
#	Time	Memory	Function	Location
1	0.2007	386864	{main}( )	...\index.php:0
2	0.2017	434288	require_once( 'C:\myproject\wp-admin\admin.php' )	...\index.php:10
3	0.2025	448320	require_once( 'C:\myproject\wp-load.php' )	...\admin.php:31
4	0.2029	477064	require_once( 'C:\myproject\wp-config.php' )	...\wp-load.php:37
5	0.2036	551784	require_once( 'C:\myproject\wp-settings.php' )	...\wp-config.php:176
6	0.2080	719672	include( 'C:\myproject\wp-content\advanced-cache.php' )	...\wp-settings.php:74
7	0.2270	1542184	w3_instance( )	...\advanced-cache.php:33
8	0.2287	1805152	W3_PgCache->__construct( )	...\define.php:1471
```
`apply_filters` is defined in plugin.php, but no plugin.php in this context.

**Comment by cesco69** [comment]
doesn't work, see https://github.com/szepeviktor/fix-w3tc/issues/70

**Pull request merged**
