### PR TITLE
Drop off from dashboard any reference to original W3 Total Cache

### PR DESCRIPTION
**Pull request by nigrosimone**
Drop off from dashboard any reference to original W3 Total Cache

Fix for https://github.com/szepeviktor/fix-w3tc/issues/60

### CODE REVIEW

**Comment by nigrosimone** [comment]
@amiga-500, @charlesLF do you agree?

**Comment by amiga-500** [comment]
Hi @nigrosimone !  On my way home right now (finally) and will have a look and let you know in a few hours.

Kimberly

**Comment by amiga-500** [comment]
Hi again @nigrosimone ... yup agreed!  Everything looks good!

**Comment by charlesLF** [comment]
@amiga-500 and @nigrosimone :

What about the code in lightbox.js, options.js, and Licensing.php?

Some of these lines are no longer needed (function `w3tc_lightbox_buy_plugin`, `w3tc_lightbox_save_licence_key`) ... We'll have to track them down and clean up any unused code.

**Comment by amiga-500** [comment]
@charlesLF  agreed.  I will begin removing them with the proverbial surgical scalpel in the coming days.

**Pull request merged**
