### PR TITLE
Trying to fix PHP 7

### LINKED ISSUE #346: Fix PHP 7.1 tests
If done please revert https://github.com/szepeviktor/w3-total-cache-fixed/commit/2cf13746ac5324058d1b61a3809c82ec8d8b2ea6

### PR DESCRIPTION
**Pull request by szepeviktor**
APCu is already in Travis' PHP7

Fixes #346

### CODE REVIEW

**Comment by szepeviktor** [comment]
@nigrosimone Could you comment on the test results?
https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/238565441

**Comment by nigrosimone** [comment]
you talking about

> 1) W3_Object_Cache_Test::test_wp_cache_switch_to_blog with data set #0 ('foo')
> This test did not perform any assertions

this happend because the specific test is only for multisite and on non-multisite not perform any assertions. see https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/tests/w3-object-cache-test.php#L217

```php
// skip test if not multisite
if( !is_multisite() ){
   return;
}
```

for hide this alert the simplest fix is:

```php
// skip test if not multisite
if( !is_multisite() ){
   $this->assertTrue( true );
   return;
}

**Comment by szepeviktor** [comment]
Thank you for your answer.
The multisite test looks almost the same.
https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/238565442

Could you sort it out? or @Furniel

**Comment by nigrosimone** [comment]
@szepeviktor i have added more test into https://github.com/szepeviktor/w3-total-cache-fixed/pull/495

- Add a check for control if w3tc plugin is activate
- Add a check for control if one of caching modules is enabled (redit, memcache, etc.)
- Add a check for multisite when we would run test for multisite

**Pull request closed without merging**
