### PR TITLE
Test on modern PHP versions

### PR DESCRIPTION
**Pull request by szepeviktor**
< 5.6 is EOL

### CODE REVIEW

**Comment by nigrosimone** [comment]
+1

**Comment by szepeviktor** [comment]
@nigrosimone Hello! How are you doing with the official releases?
Are they stealing from us?
Are you importing the official changes?

**Comment by nigrosimone** [comment]
Hi viktor! Official version seem again abbandoned :D. for my project i use fix-w3tc master, it seem very stable ;)

**Comment by szepeviktor** [comment]
@pls consider using PR-s for modifying the code base.
I've also learned it.

**Pull request merged**
