### PR TITLE
Issue template

### PR DESCRIPTION
**Pull request by nigrosimone**
Issue template update

@szepeviktor please can you fix my poor english? see https://github.com/szepeviktor/w3-total-cache-fixed/pull/432/files

### CODE REVIEW

**Comment by szepeviktor** [comment]
```markdown
Thank you for reporting an issue!

Please make sure you describe the issue and your use case.

It is helpful if you provide details of your environment:

- Webserver name and version 
- PHP version and handler type (e.g. mod_php, suPHP, PHP-FPM)
- Database server name and version
- WordPress core version
- W3 Total Cache plugin version

Please provide an error log if you can by adding these lines to your `wp-config.php`:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```` <-- remove one
WordPress puts the error log in `/wp-content/debug.log`

If you are also proposing a solution then please make sure to elaborate on why your solution is adequate.
```

**Comment by szepeviktor** [comment]
The backticks!

**Comment by szepeviktor** [comment]
😢  no backticks ....

**Comment by nigrosimone** [comment]
in the issue form are unnecessary... :(

**Comment by szepeviktor** [comment]
That's right! Sorry.

**Pull request merged**
