### PR TITLE
CSSTidy Update

### PR DESCRIPTION
**Pull request by amiga-500**
This is an update to the aging CSSTidy engine. Bumps it up to v1.5.5 (the latest) which includes support for CSS3.0.  I also added bug fixes to this engine.  And also includes a few new user-selectable options under the _Minify > CSS_ section.

This new version of CSSTidy requires at least php 5.4 and so will auto-magically disable itself (within the _General Settings > Minify > CSS minifier_ drop-down box) if that requirement is not met. :octocat:

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you!

**Comment by szepeviktor** [comment]
@nigrosimone This is my secret short-list of changes in v0.9.5.x
https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog

Would you be so kind to tell w3tc support to look for it instead of the commit log?

**Comment by nigrosimone** [comment]
Ok.. i have send a mail just now.

**Comment by szepeviktor** [comment]
Thanks 😄

**Comment by amiga-500** [comment]
@szepeviktor said
> _This is my secret short-list of changes in v0.9.5.x_
> _https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog_

I hope you don't mind me making visual tweaks to that page :stuck_out_tongue_winking_eye:

Cheers
Kimberly :octocat:

**Pull request merged**
