### PR TITLE
Feeds (rss, rss2, atom, rdf) Not Caching

### PR DESCRIPTION
**Pull request by amiga-500**
When using the `Cache Feeds` checkbox under Page Cache it is suppose to cache feeds as identified by wp's _is_feed()_ function.  However, w3tc assumed the content type of feeds was just _text/xml_ (which was true in older wp versions) but current wp iterations now set the feed content types to _application/rss+xml_, _application/atom+xml_, etc.  As such, prior to this fix w3tc did not cache any feeds (that i know of).

Also a minor tweak was made to the `Purge Sitemaps` default regex.
## Update

Ok i've just done a new commit that now allows feeds and sitemaps to return back their correct content-type (xml) when using Disk: Enhanced.  

I've done some thorough tests and it seems to work really well.  I can cache feeds (rss, rss2, atom, rdf) and retrieve them from cache properly.  Because caching feeds finally are working i recommend people use the "_Purge Policy_" checkboxes to manage when these cached feeds get cleared (e.g., when its associating post is updated or a new comment is made).

I verified that minify for sitemaps and feeds work very well.  I tested these minified files against W3C Feed Verification service and they passed.

I also fixed a [php warning notice](https://github.com/szepeviktor/fix-w3tc/pull/85/files#diff-9751a09488be6cf7208ade6039decb96R170) in Minify.php that occured when attempting to minify an xml file.  It was looking for a _<head>_ tag when none exists for xml files.

I added a new option `Handle XML mime type` under _Advanced_ of Page Cache which is checked on by default that, as the name suggests, is for handling the feeds/sitemap content-type issue.  I figured maybe someone might want the ability to toggle this and make it revert back to w3tc's old way (all returned content is treated as if it were html).

By default, I placed a sitemap regex entry into the _Never Cache the Following Pages_ by default.  I did this as a precaution in case, on first install, someone doesn't want their sitemaps to be cached.  So it is up to them to remove this regex entry for sitemaps to begin caching.

### CODE REVIEW

**Comment by amiga-500** [comment]
Interesting side note:  When using Disk Enhanced w3tc always stores feeds and xml sitemaps as _index.html_, regardless of content type.  Because w3tc does not have any way of identifying what that content type was after being stored as _index.html_ it always serves back all pages as content type: _text/html_.  In other words, it doesn't set the **Content-Type:** header for Disk Enhanced responses and so the server decides based on the file extension.  As such, xml sitemaps which are suppose to return content-type: _text/xml_ or rdf feeds as _application/rdf+xml_, will both return as _text/html_ to the client.  This will render client-side results visually incorrect even though the contents of that result will be proper.  So its not a problem with the content it is a problem with the returning mime type being set (or more correctly, not being set) for Disk Enhanced.

I'm not really sure what to do yet (disk enhanced is a bit tricky).  My running idea would be to save the proper extension just before the _.html_ suffix since it is at this moment in time that disk enhanced does know what the content type really is...so e.g., instead of _index.html_ it would now be _index**.xml**.html_ for xml file types.  And, because disk enhanced depends on htaccess/nginx rule(s) heavily, identify if the _.xml, .atom, .rss, .rdf_ extension exists in the filename (it checks that the file exists in the cache dir via "_-f_" and sets an environment variable e.g. _RewriteRule .* - [E=ext:rss]_) and if it does then do something like a _Header set Content-Type {ENV:ext}_ just before feeding back the cached content.  Dunno if that would work.  I'll have to do some more thinking about it.

**Comment by vijayaraghavanramanan** [comment]
Hi @amiga-500,  

The way I have been able to deal with the rss feed and sitemap is to add the following in "never cache the following pages" and "never minify the following pages":

```
sitemap(_index)?\.xml(\.gz)?
([a-z0-9_\-]+)?sitemap\.xsl
[a-z0-9_\-]+-sitemap([0-9]+)?\.xml(\.gz)?
```

After this patch, will I then be able to remove them and enjoy sitemap/feed caching?

**Comment by amiga-500** [comment]
> _After this patch, will I then be able to remove them and enjoy sitemap/feed caching?_

Hi @vijayaraghavanramanan ... not quite yet :(  Actually, all this patch does is allow for feeds (rss, rss2, atom, rdf) to finally get stored to disk when one enables the `Cache Feeds: Site, Categories, Tags, Comments` option under Page Cache.  Prior to this, i noticed that even if one checkmarked it on it would never cache feeds.  Now with this patch, when for example Disk Enhanced is used you will see a new directory called _feed_ created and depending on the feed type another subfolder is created e.g. _rdf_ where its cache file resides.  

As for your regex lines for sitemap under _Never cache_ and _Never Minify_:  I'd recommend leaving them in for now.  I'm doing another patch that assists Disk Enhanced for returned xml and feed cache files.  At present, cached sitemaps and feeds all return back as html instead of their correct content type which causes the browser (at least in Firefox and Chrome) to display messy.  This is why i wouldn't use caching for them just yet even though they cache fine.  It's how its being returned which is the problem.  Using Disk Basic mode none of this is a problem (this patch now allows it too to cache feeds) -- it all caches and returns correctly.

Of course, it'll always be important to use the `Purge Sitemap` field, and the `Specify the Feed Types to Purge` checkboxes if one does decide to cache sitemaps and feeds so that when a post is created/edited they can be flushed and new sitemaps/feeds are generated.

Cheers
Kimberly

**Comment by amiga-500** [comment]
Hi again @vijayaraghavanramanan ... did another commit into this PR and now it has the ability to return back the proper content-type for sitemaps and feeds.  Did some tests.  Works well. 

Gotta ask ... for your sitemap regex entry under "_Never Cache_" is it because w3tc would cache your sitemap but never purge it?  Under "_Purge Sitemaps_" do you have something like : **`[a-z0-9_\-]*sitemap[a-z0-9_\-]*\.(xml|xsl|html?)(\.gz)?`** ? Notice it even looks to purge a sitemap's _.xsl_ stylesheet and a _gz_ compression file if they exist.   I figure with something like that in the box one can be more assured that the sitemap will get cleared whenever any change happened on the site.   Of course this is putting aside things like browser cache lifetime settings and server-side cache software like Varnish.  Technically, one could just type **`sitemap`** and accomplish the same thing without the need for all that regex mumbo-jumbo in the box and it would purge all files that had the word _sitemap_ in it but if a post had that name too then bye-bye post cache. 

Anyway, also did some tests and found minification works for sitemaps and feeds caching too.  Validates in W3C's Feed Validator tool.

Thanks for the info and have a great day!
Kimberly

**Comment by vijayaraghavanramanan** [comment]
Hi @amiga-500 

> Gotta ask ... for your sitemap regex entry under "Never Cache" is it because w3tc would cache your sitemap but never purge it?

I use it because it messes up my feeds and sitemaps. The output looks garbled in the case of sitemaps and looks like HTML for feeds and even downloads images which feeds aren't supposed to do. 

> Under "Purge Sitemaps" do you have something like : `[a-z0-9_\-]*sitemap[a-z0-9_\-]*\.(xml|xsl|html?)(\.gz)? ? `

I have this `([a-z0-9_\-]*?)sitemap([a-z0-9_\-]*)?\.xml`

Ideally, it's good to have sitemaps and feeds cached as bots try to request them but in the current state, it's difficult to do so. 

Have a nice day too!

**Comment by amiga-500** [comment]
Ahh that makes sense.  Yea it sounds like the garbled thing you are experiencing is exactly what caused me to make this patch.  Now my sitemap and feeds are displaying fine and caching/minifying.  The new "_Handle XML Mime Type_" checkbox i added is what solved it for me.  I'll likely merge the patch into _master_ tomorrow.

It's interesting that you've been able to get feeds to cache at all.  For a long time i have never been able to do that.  I found an error in the W3TC's code that when fixed i was finally able to begin caching all the feeds types.

**Comment by nigrosimone** [comment]
@amiga-500 you can do the merge by herself if you think is right :)

**Comment by amiga-500** [comment]
> @amiga-500 you can do the merge by herself if you think is right :)

Thanks! And done.!

**Pull request merged**
