### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by Furniel**

### CODE REVIEW

**Comment by nigrosimone** [comment]
@Furniel please, same as https://github.com/szepeviktor/w3-total-cache-fixed/pull/478 with plus:

- Make a separate PR of each single bug fix/improvements;
- Make a useful description, `No description provided` it's bad;

Thanks ;)

**Comment by szepeviktor** [comment]
@Furniel We appreciate your work.
Please keep this repo clean. Thanks!

**Comment by nigrosimone** [comment]
@Furniel are you still interested to open separate PRs?

**Comment by szepeviktor** [comment]
If it is an unbearable burden to execute the above please notify us, we may help.

**Comment by Furniel** [comment]
I'll create separate PRs later this week(Worked all weekend on minify lib update, found some serious issues with js minification(not related to update, all issues exist in original version.) Unfortunately I wasted whole weekend but still didn't found reason of bugs.).

**Comment by nigrosimone** [comment]
> Unfortunately I wasted whole weekend but still didn't found reason of bugs.

@Furniel open an [issue](https://github.com/szepeviktor/w3-total-cache-fixed/issues/new), maybe another poit of view can help.

**Pull request closed without merging**
