### PR TITLE
Write cache files in binary to prevent corruption of UTF-8 characters

### PR DESCRIPTION
**Pull request by jikamens**
Some of my cached pages ended up with garbage characters in them. Turning off the page cache made the garbage characters go away. I looked at the page cache code, and it reads and writes cache files in ASCII mode, which corrupts UTF-8 characters in them. I modified the cache code to read and write cache files in binary. Simple change, should be innocuous, seems to solve the problem.

### CODE REVIEW

**Comment by nigrosimone** [comment]
@jikamens thanks, but unit testing has failed and i can't merge your pr without a successful testing. Please try again (with a new commit), the failed test seem not correlate to your commit.

**Comment by jikamens** [comment]
I'm confused, are you saying I should just close this PR and resubmit a new one with the hope that the unit tests will pass the next time?

**Comment by nigrosimone** [comment]
or you can commit add a new line into the changelog (README.md) at the end of the file, eg.:

    :beetle: Bug Fix | [Write cache files in binary to prevent corruption of UTF-8 characters](https://github.com/szepeviktor/w3-total-cache-fixed/pull/527) |

**Comment by jikamens** [comment]
Welp. I don't see what I can do about a Travis failure that's unrelated to my changes...

**Comment by nigrosimone** [comment]
@jikamens thanks for your pr and your patience. I will merge your pr when i fix travis.

**Pull request merged**
