### PR TITLE
YUI Compressor: Fix for Empty JAVA executable path and JAVA path with spaces

### PR DESCRIPTION
**Pull request by nigrosimone**
Two fix here.

1. W3TC on "Test YUI Compressor" always return "Empty JAVA executale path"

2. If java path has spaces (very common on windows) doesn't works

immagine2

### CODE REVIEW

**Comment by MakarkinPRO** [comment]
How to apply that Fix to my W3 total cache plugin?

**Comment by nigrosimone** [comment]
@MakarkinPRO sorry for the delay. You have some options:

1. you can replicate the same change here https://github.com/szepeviktor/w3-total-cache-fixed/pull/426/files on your website in the same files in the same way.

2. you can download these files and replace on your website in `/wp-content/plugins/w3-total-cache/`:
 - [lib/Minify/Minify/YUICompressor.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/lib/Minify/Minify/YUICompressor.php)
 - [pub/js/options.js](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/pub/js/options.js)

3. you can install W3 Total Cache Fixed instead of W3 Total Cache. Download the [master](https://github.com/szepeviktor/w3-total-cache-fixed/archive/v0.9.5.x.zip), and follow this steps for install it https://github.com/szepeviktor/w3-total-cache-fixed#installation-for-v095x-users . This community version has some others bug fix see: https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog.

**Comment by MakarkinPRO** [comment]
Thx. Cool manual for me!

**Comment by MakarkinPRO** [comment]
Looks like still have same issue (follow step 2)

**Comment by nigrosimone** [comment]
try to delete your browser cache for use the fresh version of `pub/js/options.js`.

**Comment by MakarkinPRO** [comment]
Heh. Yes. That works! Just last 2 questions YUI work good with NGINX and it's the best for CSS/JS minifing?

**Comment by nigrosimone** [comment]
> YUI work good with NGINX 

Yui isn't a webserver's tool: it works on nginx, apache and iis without any difference. 

> it's the best for CSS/JS minifing?

I don't know if it's the best, but it's good.

**Comment by MakarkinPRO** [comment]
When I'm activating it all my Site looks ugly probably becaouse CSS and JS not loaded correctly) But it's loading faster)

**Comment by nigrosimone** [comment]
I think yui fails in minification. Sometime if yui try to minify already minified file it fails. in this case the only option is use standard minifier.

**Pull request merged**
