### PR TITLE
Travis integration plus unit testing

### PR DESCRIPTION
**Pull request by nigrosimone**
First implementation for unit test. Issue https://github.com/szepeviktor/fix-w3tc/issues/44

### CODE REVIEW

**Comment by nigrosimone** [comment]
@szepeviktor have you an account on Travis? i want integrate units testing in this project. 

with this PR i have make a basic configuration for travis

Please, can you allow this project on Travis?

**Comment by szepeviktor** [comment]
Close&reopen to fire up Travis!

**Comment by szepeviktor** [comment]
https://travis-ci.org/szepeviktor/fix-w3tc/builds/161619113

**Comment by szepeviktor** [comment]
Please fix this t: https://travis-ci.org/szepeviktor/fix-w3tc/jobs/161619123#L211

**Comment by szepeviktor** [comment]
And support PHP and WP as in https://github.com/wp-cli/wp-cli/blob/master/.travis.yml#L10

**Pull request merged**
