### PR TITLE
Accepted query strings in page cache enhanced

### PR DESCRIPTION
**Pull request by nigrosimone**
Add support fo accepted query strings in page cache enhanced  mode

Feature Request https://github.com/szepeviktor/w3-total-cache-fixed/issues/221

### CODE REVIEW

**Comment by nigrosimone** [comment]
waiting for community review...

**Comment by amiga-500** [comment]
Wow...wonderful feature.  I will review it later today (out and about buying last minute xmas presents)

**Comment by amiga-500** [comment]
Hi @nigrosimone  i did some adjustments to your code to include a section for nginx too: [commit](https://github.com/szepeviktor/w3-total-cache-fixed/compare/amiga-qs-pc-enhanced?expand=1#diff-8ba320bb61c892de34b1de433dfa14c4) .  

However, i discovered some issues...

The _Accepted Query Strings_ field allows for regex entries.  So entries such as the following are permitted by w3tc:
```
utm_source
utm_source=foo
utm_source=.*
utm_source=(foo|bar)
```
Because of that i was thinking your line:
```php
$rules .= "    RewriteCond %{ENV:CustomQueryString} ^(.*)&?".$query_string."=[^&]+&?(.*)$ [NC]\n";
```
Might be better as:
```php
$rules .= "    RewriteCond %{ENV:CustomQueryString} ^(.*)&?".$query_string."[^&]*&?(.*)$ [NC]\n";
```
Notice i removed the "=" and replaced the "+" with "*"

However, even with the change the user would still have to be careful since if they did something like `utm_source=.*` it would fail because it should be `utm_source=.*?` and something like `utm_source=(foo|bar)` would have to be `utm_source=(?:foo|bar)` because of the `$2` would get mismatched.  I figure it's not a big deal since most people probably wont get too intense with regex in that field.

I didn't do a Push Request yet.  Figured to show you the changes first so we can make any further adjustments.

**Comment by nigrosimone** [comment]
> some adjustments to your code to include a section for nginx too

awersome!

> even with the change the user would still have to be careful 

this is dangerous... if user broken htaccess compiling, the website goes down and show white screen of dead. i think it's better specify it in the dashboard with a "strong" label under the textarea.

**Comment by amiga-500** [comment]
> _this is dangerous... if user broken htaccess compiling, the website goes down and show white screen of dead. i think it's better specify it in the dashboard with a "strong" label under the textarea._

I'll definitely do that.

**Comment by amiga-500** [comment]
Since i have a branch that is a clone of this branch but with newer tweaks i figure this PR shouldnt be squashed/merged but simply Closed and just Push my branch instead.  So i will do that.

**Comment by nigrosimone** [comment]
yeah! maybe with practical examples like:
foo=.*? 
foo=(?:bar|baz)

**Pull request closed without merging**
